apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:18
        ports:
          - containerPort: 8069
        env:
          - name: HOST
            value: "postgres-service"
          - name: PORT
            value: "5432"
          - name: USER
            value: "odoo"
          - name: PASSWORD
            value: "odoo"
      volumes:
        - name: odoo-config
          configMap:
            name: odoo-config