apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # Permite que o volume seja montado por um único nó em modo de leitura e escrita de cada vez
  resources:
    requests:
      storage: 1Gi
